#!/usr/bin/env python3
from __future__ import annotations

"""
prepare_boltz_inputs.py

Extract peptide sequences from ODesign output CIF files and generate
Boltz-2 YAML input files for structure + affinity prediction.

Usage:
    python prepare_boltz_inputs.py \\
        --odesign-output $SCRATCH/odesign/outputs/mdm2_cyclic \\
        --output-dir $SCRATCH/boltz/inputs/odesign_eval \\
        --n-designs 5

Compatible with Python 3.9+.
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple, Optional

# MDM2 residues 17-125 (matching 1YCR crystal structure construct used
# as the ODesign target). UniProt Q00987.
MDM2_SEQUENCE = (
    "SQIPASEQETLVRPKPLLLKLLKSVGAQKDTYTMKEVLFYLGQYIMTKRLYDEKQQHIVYC"
    "SNDLLGDLFGVPSFSVKEHRKIYTMIYRNLVVVNQQESSDSGTSVSEN"
)

# Three-letter to one-letter amino acid mapping
AA_3TO1 = {
    "ALA": "A", "ARG": "R", "ASN": "N", "ASP": "D", "CYS": "C",
    "GLN": "Q", "GLU": "E", "GLY": "G", "HIS": "H", "ILE": "I",
    "LEU": "L", "LYS": "K", "MET": "M", "PHE": "F", "PRO": "P",
    "SER": "S", "THR": "T", "TRP": "W", "TYR": "Y", "VAL": "V",
}


def extract_chain_sequences(cif_path: Path) -> Dict[str, str]:
    """
    Parse a CIF file and return a dict mapping chain ID to one-letter sequence.
    """
    chains: Dict[str, List[Tuple[int, str]]] = {}
    in_atom_site = False
    column_names: List[str] = []

    with cif_path.open() as f:
        for line in f:
            line = line.rstrip()

            if line.startswith("loop_"):
                column_names = []
                in_atom_site = False
                continue

            if line.startswith("_atom_site."):
                column_names.append(line.split(".", 1)[1].strip())
                if "group_PDB" in line or "label_atom_id" in line:
                    in_atom_site = True
                continue

            if not in_atom_site:
                continue

            if line.startswith("#") or not line.strip():
                in_atom_site = False
                continue

            if not (line.startswith("ATOM") or line.startswith("HETATM")):
                in_atom_site = False
                continue

            fields = line.split()
            if len(fields) < len(column_names):
                continue

            row = dict(zip(column_names, fields))
            atom_name = row.get("label_atom_id", "").strip('"')
            if atom_name != "CA":
                continue

            chain_id = row.get("label_asym_id", "")
            try:
                seq_id = int(row.get("label_seq_id", "0"))
            except ValueError:
                continue

            resname = row.get("label_comp_id", "").upper()
            if resname not in AA_3TO1:
                continue

            chains.setdefault(chain_id, []).append((seq_id, resname))

    result: Dict[str, str] = {}
    for chain_id, residues in chains.items():
        residues.sort(key=lambda x: x[0])
        result[chain_id] = "".join(AA_3TO1[r[1]] for r in residues)

    return result


def identify_designed_chain(
    chain_seqs: Dict[str, str],
    target_seq: str,
    design_length_hint: int = 10
) -> Optional[str]:
    """
    Identify which chain in the CIF is the designed cyclic peptide.

    The designed chain should be short (near design_length_hint) and
    should not appear as a substring of the MDM2 target sequence.
    """
    for chain_id, seq in chain_seqs.items():
        if len(seq) <= design_length_hint + 5 and seq not in target_seq:
            return chain_id
    return None


def find_prediction_cifs(odesign_output_dir: Path) -> List[Path]:
    """
    Walk the ODesign output directory tree and return all prediction CIF
    files from the most recent timestamp directory.
    """
    cifs: List[Path] = []

    timestamp_dirs = sorted(
        [p for p in odesign_output_dir.iterdir() if p.is_dir()],
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not timestamp_dirs:
        return []

    latest_run = timestamp_dirs[0]
    print(f"Using ODesign run: {latest_run.name}", file=sys.stderr)

    for predictions_dir in sorted(latest_run.rglob("predictions")):
        for cif in sorted(predictions_dir.glob("*.cif")):
            cifs.append(cif)

    return cifs


def write_boltz_yaml(
    output_path: Path,
    peptide_sequence: str,
    design_id: str
) -> None:
    """
    Write a Boltz-2 YAML input file for MDM2 + cyclic peptide.

    Note: Boltz-2's affinity head is trained on drug-like small molecules
    and is not reliable for large peptidic binders. We request only
    structure prediction here and rely on MM-GBSA for binding energy.
    """
    yaml_content = f"""# Boltz-2 input for MDM2 + ODesign cyclic peptide candidate
# Source design: {design_id}
# Generated by prepare_boltz_inputs.py
#
# Note: affinity prediction is deliberately NOT requested here because
# Boltz-2's affinity head was trained on drug-like small molecules and
# does not produce reliable values for cyclic peptide binders
# (~100 heavy atoms >> 50 atom guideline from the Boltz-2 authors).
# We compute binding energies with MM-GBSA instead.

version: 1
sequences:
  - protein:
      id: MDM2
      sequence: {MDM2_SEQUENCE}
  - protein:
      id: PEP
      sequence: {peptide_sequence}
      cyclic: true
"""
    output_path.write_text(yaml_content)


def main():
    parser = argparse.ArgumentParser(
        description="Prepare Boltz-2 YAML inputs from ODesign outputs",
    )
    parser.add_argument("--odesign-output", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--n-designs", type=int, default=5)
    parser.add_argument("--design-length", type=int, default=12)
    parser.add_argument(
        "--min-length",
        type=int,
        default=7,
        help="Minimum peptide length to accept in residues (default: 7). "
             "Designs shorter than this are skipped for synthetic "
             "accessibility reasons.",
    )
    args = parser.parse_args()

    if not args.odesign_output.is_dir():
        print(f"Error: {args.odesign_output} is not a directory", file=sys.stderr)
        sys.exit(1)

    cifs = find_prediction_cifs(args.odesign_output)
    if not cifs:
        print(f"Error: no prediction CIFs found under {args.odesign_output}",
              file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(cifs)} prediction CIFs", file=sys.stderr)

    args.output_dir.mkdir(parents=True, exist_ok=True)

    manifest_lines = ["# design_id\tsource_cif\tpeptide_sequence\tboltz_yaml"]
    accepted = 0
    skipped_short = 0
    skipped_other = 0

    print(f"Selecting up to {args.n_designs} designs with length >= "
          f"{args.min_length} residues", file=sys.stderr)

    for cif in cifs:
        if accepted >= args.n_designs:
            break

        chain_seqs = extract_chain_sequences(cif)
        if not chain_seqs:
            print(f"  SKIP: no chains extracted from {cif.name}",
                  file=sys.stderr)
            skipped_other += 1
            continue

        designed = identify_designed_chain(
            chain_seqs, MDM2_SEQUENCE, args.design_length
        )
        if designed is None:
            print(f"  SKIP: could not identify designed chain in "
                  f"{cif.name} (chains: {list(chain_seqs.keys())})",
                  file=sys.stderr)
            skipped_other += 1
            continue

        peptide_seq = chain_seqs[designed]

        if len(peptide_seq) < args.min_length:
            print(f"  SKIP: {cif.name} peptide too short "
                  f"({len(peptide_seq)} < {args.min_length}): {peptide_seq}",
                  file=sys.stderr)
            skipped_short += 1
            continue

        accepted += 1
        seed_match = re.search(r"seed_(\d+)", str(cif))
        seed_tag = f"seed{seed_match.group(1)}" if seed_match else "seedXXX"
        design_id = f"design_{accepted:02d}_{seed_tag}"

        yaml_path = args.output_dir / f"{design_id}.yaml"
        write_boltz_yaml(yaml_path, peptide_seq, design_id)

        print(f"  [{accepted}] {design_id}: {peptide_seq} "
              f"({len(peptide_seq)} aa) -> {yaml_path.name}",
              file=sys.stderr)
        manifest_lines.append(
            f"{design_id}\t{cif}\t{peptide_seq}\t{yaml_path}"
        )

    if accepted < args.n_designs:
        print(f"\nWARNING: only {accepted}/{args.n_designs} designs accepted "
              f"(short: {skipped_short}, other: {skipped_other}). "
              f"Consider running ODesign with more seeds/samples.",
              file=sys.stderr)

    # Write manifest to the parent of the YAML directory so that Boltz-2
    # does not try to parse it as a prediction input (Boltz processes
    # every file in its input directory).
    manifest_path = args.output_dir.parent / f"{args.output_dir.name}_manifest.tsv"
    manifest_path.write_text("\n".join(manifest_lines) + "\n")
    print(f"\nWrote manifest: {manifest_path}", file=sys.stderr)
    print(f"Wrote {len(manifest_lines) - 1} YAML files to {args.output_dir}",
          file=sys.stderr)


if __name__ == "__main__":
    main()
